/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as Profile2FAuthenticationRouteImport } from './routes/profile/2FAuthentication'
import { Route as Profile2FAuthenticationVerifyRouteImport } from './routes/profile/2FAuthenticationVerify'
import { Route as ProfilePhoneIndexRouteImport } from './routes/profile/phone/index'
import { Route as ProfilePhoneVerifyRouteImport } from './routes/profile/phone/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/success.lazy').then((d) => d.Route))
const Profile2FAuthenticationRoute = Profile2FAuthenticationRouteImport.update({
  id: '/profile/2FAuthentication',
  path: '/profile/2FAuthentication',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/profile/2FAuthentication.lazy').then((d) => d.Route),
)
const Profile2FAuthenticationVerifyRoute =
  Profile2FAuthenticationVerifyRouteImport.update({
    id: '/profile/2FAuthenticationVerify',
    path: '/profile/2FAuthenticationVerify',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/profile/2FAuthenticationVerify.lazy').then((d) => d.Route),
  )
const ProfilePhoneIndexRoute = ProfilePhoneIndexRouteImport.update({
  id: '/profile/phone/',
  path: '/profile/phone/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/profile/phone/index.lazy').then((d) => d.Route),
)
const ProfilePhoneVerifyRoute = ProfilePhoneVerifyRouteImport.update({
  id: '/profile/phone/verify',
  path: '/profile/phone/verify',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/profile/phone/verify.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/profile/2FAuthentication': typeof Profile2FAuthenticationRoute
  '/profile/2FAuthenticationVerify': typeof Profile2FAuthenticationVerifyRoute
  '/profile/phone/verify': typeof ProfilePhoneVerifyRoute
  '/profile/phone/': typeof ProfilePhoneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/profile/2FAuthentication': typeof Profile2FAuthenticationRoute
  '/profile/2FAuthenticationVerify': typeof Profile2FAuthenticationVerifyRoute
  '/profile/phone/verify': typeof ProfilePhoneVerifyRoute
  '/profile/phone': typeof ProfilePhoneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/profile/2FAuthentication': typeof Profile2FAuthenticationRoute
  '/profile/2FAuthenticationVerify': typeof Profile2FAuthenticationVerifyRoute
  '/profile/phone/verify': typeof ProfilePhoneVerifyRoute
  '/profile/phone/': typeof ProfilePhoneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/success'
    | '/profile/2FAuthentication'
    | '/profile/2FAuthenticationVerify'
    | '/profile/phone/verify'
    | '/profile/phone/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/success'
    | '/profile/2FAuthentication'
    | '/profile/2FAuthenticationVerify'
    | '/profile/phone/verify'
    | '/profile/phone'
  id:
    | '__root__'
    | '/'
    | '/success'
    | '/profile/2FAuthentication'
    | '/profile/2FAuthenticationVerify'
    | '/profile/phone/verify'
    | '/profile/phone/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuccessRoute: typeof SuccessRoute
  Profile2FAuthenticationRoute: typeof Profile2FAuthenticationRoute
  Profile2FAuthenticationVerifyRoute: typeof Profile2FAuthenticationVerifyRoute
  ProfilePhoneVerifyRoute: typeof ProfilePhoneVerifyRoute
  ProfilePhoneIndexRoute: typeof ProfilePhoneIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/2FAuthentication': {
      id: '/profile/2FAuthentication'
      path: '/profile/2FAuthentication'
      fullPath: '/profile/2FAuthentication'
      preLoaderRoute: typeof Profile2FAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/2FAuthenticationVerify': {
      id: '/profile/2FAuthenticationVerify'
      path: '/profile/2FAuthenticationVerify'
      fullPath: '/profile/2FAuthenticationVerify'
      preLoaderRoute: typeof Profile2FAuthenticationVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/phone/': {
      id: '/profile/phone/'
      path: '/profile/phone'
      fullPath: '/profile/phone/'
      preLoaderRoute: typeof ProfilePhoneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/phone/verify': {
      id: '/profile/phone/verify'
      path: '/profile/phone/verify'
      fullPath: '/profile/phone/verify'
      preLoaderRoute: typeof ProfilePhoneVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuccessRoute: SuccessRoute,
  Profile2FAuthenticationRoute: Profile2FAuthenticationRoute,
  Profile2FAuthenticationVerifyRoute: Profile2FAuthenticationVerifyRoute,
  ProfilePhoneVerifyRoute: ProfilePhoneVerifyRoute,
  ProfilePhoneIndexRoute: ProfilePhoneIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
